# Windows Logs Index
[win_logs]
homePath   = $SPLUNK_DB/win_logs/db
coldPath   = $SPLUNK_DB/win_logs/colddb
thawedPath = $SPLUNK_DB/win_logs/thaweddb

# Sysmon Logs Index
[sysmon]
homePath   = $SPLUNK_DB/sysmon/db
coldPath   = $SPLUNK_DB/sysmon/colddb
thawedPath = $SPLUNK_DB/sysmon/thaweddb
