# Windows Event Log Inputs
[WinEventLog://Security]
disabled = 0
index = win_logs

[WinEventLog://System]
disabled = 0
index = win_logs

[WinEventLog://Application]
disabled = 0
index = win_logs

# Sysmon Operational Logs
[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = sysmon
