# Normalize Windows Event Logs
[WinEventLog:Security]
SHOULD_LINEMERGE = false

[WinEventLog:System]
SHOULD_LINEMERGE = false

[WinEventLog:Application]
SHOULD_LINEMERGE = false

# Normalize Sysmon
[XmlWinEventLog:Microsoft-Windows-Sysmon/Operational]
SHOULD_LINEMERGE = false
INDEXED_EXTRACTIONS = xml
